apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-account
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: service-discovery-role
subjects:
- kind: ServiceAccount
  name: prometheus-account
  namespace: monitoring
