{
 "title": "API Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "Application",
    "query": {
     "query": "label_values(kubernetes_service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_duration_seconds_count{kubernetes_service=\"$app\"}[1m])*60) by(path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(path) (http_requests_duration_seconds_count{kubernetes_service=\"$app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(method, path, status) (sort_desc(http_requests_duration_seconds_sum{kubernetes_service=\"$app\"}) / http_requests_duration_seconds_count{kubernetes_service=\"$app\"})",
     "legendFormat": "({{status}}) {{path}}"
    }
   ]
  },
  {
   "title": "Request Error Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_duration_seconds_count{kubernetes_service=\"$app\", status=~\"5.*|\"})/sum(http_requests_duration_seconds_count{kubernetes_service=\"$app\"})"
    }
   ]
  },
  {
   "title": "WS Duration (Top)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(max by(client_id) (websocket_connected_duration_seconds_sum{kubernetes_service=\"$app\"}))",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "WS Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(websocket_connections_total{kubernetes_service=\"$app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WS Duration (Avg)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (sort_desc(websocket_connected_duration_seconds_sum{kubernetes_service=\"$app\"}))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}