apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-server
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: jaeger-server
  template:
    metadata:
      labels:
        app: jaeger-server
    spec:
      containers:
      - name: jaeger-server
        image: jaegertracing/all-in-one:latest
        env:
          - name: "COLLECTOR_OTLP_ENABLED"
            value: "true"
          - name: "METRICS_STORAGE_TYPE"
            value: "prometheus"
          - name: "PROMETHEUS_SERVER_URL"
            value: "http://prometheus-service:9090"
          - name: "PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR"
            value: "true"
          - name: "PROMETHEUS_QUERY_NORMALIZE_CALLS"
            value: "true"
          - name: "PROMETHEUS_QUERY_NORMALIZE_DURATION"
            value: "true"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
          - containerPort: 4317 # collector - OTLP gRPC
            protocol: TCP
          - containerPort: 4318 # collector - OTLP HTTP
            protocol: TCP
          - containerPort: 16686 # query - frontend
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
  namespace: monitoring
spec:
  type: ClusterIP
  selector:
    app: jaeger-server
  ports:
    - port: 4317
      name: jaeger-collector-otlp-grpc
      protocol: TCP
    - port: 4318
      name: jaeger-collector-otlp-http
      protocol: TCP
    - port: 16686
      name: jaeger-http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-port
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: jaeger-server
  ports:
    - name: jaeger-web
      protocol: TCP
      port: 16686
      nodePort: 30002
